# Generated by Django 5.2.4 on 2025-07-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_aboutsection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutsection',
            old_name='banner_image',
            new_name='banner',
        ),
        migrations.RenameField(
            model_name='aboutsection',
            old_name='image_1',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='aboutsection',
            old_name='image_2',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='aboutsection',
            old_name='image_3',
            new_name='image3',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='title',
        ),
    ]
