# Generated by Django 5.2.4 on 2025-07-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_banner_image_aboutsection_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='thumb',
            field=models.ImageField(default='services/default.jpg', upload_to='services/'),
        ),
    ]
