# Generated by Django 5.2.4 on 2025-07-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_project_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='services/default.jpg', upload_to='services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.CharField(default='coming soon', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(default='Coming soon'),
        ),
    ]
