# Generated by Django 5.2.4 on 2025-07-24 13:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_product_category_remove_subcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
